Beis.WebApplication/Beis.WebApplication/Controllers/ApplicantEmailAddressController.cs
namespace Beis.WebApplication.Controllers
{
    public class ApplicantEmailAddressController : BaseController<EmailAddressViewModel>
    {
        public ApplicantEmailAddressController(ILogger<ApplicantEmailAddressController> logger, IHttpContextAccessor httpContextAccessor, ISessionService sessionService) : base(logger, httpContextAccessor, sessionService)
        {
        }

        [HttpGet(RoutePaths.ApplicantEmailAddressPage, Name = RouteNames.ApplicantEmailAddressPage)]
        public IActionResult Index()
        {
            var model = base.LoadDtoAndModelFromSession();
            return View(model);
        }
        
        [HttpPost(RoutePaths.ApplicantEmailAddressPage, Name = RouteNames.ApplicantEmailAddressPage)]
        [ValidateAntiForgeryToken]

        public IActionResult Index(EmailAddressViewModel model)
        {
            if (!ModelState.IsValid || string.IsNullOrWhiteSpace(model.EmailAddress) || base.StoreDtoAndModelToSession(model).IsFailed) // model state validity evaluated incorrectly in unit test!
            {
                return View(nameof(Index), model);
            }
            return RedirectToRoute(RouteNames.ConfirmEmailAddressPage);
        }

        public override EmailAddressViewModel MapDtoToModel(EmailAddressViewModel model)
        {
            model.EmailAddress = dto.ApplicantEmailAddress;
            return model;
        }

        public override void MapModelToDto(EmailAddressViewModel model)
        {
            dto.ApplicantEmailAddress = model.EmailAddress;
        }

    }
}

Beis.WebApplication/Beis.WebApplication/Controllers/VerifyEmailAddressController.cs
using Beis.Common.Constants;
using Beis.Common.Models;
using Beis.Common.Services;
using System.Web;

namespace Beis.WebApplication.Controllers
{
    public class VerifyEmailAddressController : Controller
    {
     
        private readonly IEmailVerificationService _emailVerificationService;
        private readonly IRestoreSessionService _restoreSessionService;

        public VerifyEmailAddressController(IEmailVerificationService emailVerificationService, IRestoreSessionService restoreSessionService)
        {

            _emailVerificationService = emailVerificationService;
            _restoreSessionService = restoreSessionService;
        }

        [Route(RoutePaths.VerifyEmailAddressPage, Name = RouteNames.VerifyEmailAddressPage)]
        public async Task<IActionResult> Index(EmailVerificationModel model)
        {

            var emailAddress = HttpUtility.UrlDecode(model.EmailAddress);
            var result = await _emailVerificationService.VerifyEnterpriseFromLinkAsync(model);

            if (result.IsSuccess)
            {
                await restoreSessionFromDb(emailAddress);
                return RedirectToRoute(model.Target);
            }
                

            await _emailVerificationService.SendVerifyEmailNotificationAsync(emailAddress, model.Target);
            
            if (result.HasError<ExpiredCodeError>())
                return View("InvalidCode"); // Todo make an expired view
            
            return View("InvalidCode");
           
        }

        private async Task restoreSessionFromDb(string emailAddress)
        {
            await _restoreSessionService.RestoreSessionFromDb(emailAddress);
        }
    }
}

Beis.WebApplication/Beis.WebApplication/Views/VerifyEmailAddress/InvalidCode.cshtml
@{
    ViewData["Title"] = "The link is not valid. Please try again.";
}

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">There was a problem verifying your email address.</h1>
            <p class="govuk-body">The link is not valid. Please try again.</p>
            <p class="govuk-body"><a asp-action="" asp-controller="Home" class="govuk-link">Start the application process again</a></p>
        </div>
    </div>

Beis.WebApplication/Beis.WebApplication/Views/VerifyEmailAddress/NotVerified.cshtml
@{
    ViewData["Title"] = "There was a problem verifying your email address";
}

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">There was a problem verifying your email address.</h1>
            <p class="govuk-body">Your email address is not verified.</p>
            <p class="govuk-body">Select the link in the email to continue with your application.</p>
            <h2 class="govuk-heading-m">I didn't get the email</h2>
            <p class="govuk-body">Check your junk email folder. If the email is not there:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>you can <a asp-controller="ApplicantEmailAddress" asp-action="" class="govuk-link">enter your work email address again</a></li>
                <li>we can <a asp-controller="ApplicantEmailAddress" asp-action="CheckEmailAddress" class="govuk-link">resend the email</a></li>
            </ul>
        </div>
    </div>

Beis.WebApplication/Beis.WebApplication/Views/VerifyEmailAddress/Success.cshtml
@{
    ViewData["Title"] = "You've confirmed your email address";
}

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">You've confirmed your email address</h1>
            <p class="govuk-body">You can now apply for your software discount.</p>
            <div class="govuk-inset-text">If you apply, we will check your company details. This will not affect your credit score.</div>
            <form class="form" asp-action="Index" asp-controller="CheckEligibility">
                <input type="hidden" id="company-number" value="">
                <button ga-data-action-id="btn-sme-experian-check-success" class="govuk-button" id="experian-check" data-module="govuk-button">Apply</button>
            </form>
        </div>
    </div>